### ISSUE TITLE
QPID: seg fault seen in pn_class_compare when using broker

### ISSUE THREAD

**Issue by MattMulhern** [OpenMAMA/OpenMAMA#156]
Core seems to be occurring within qpid libs. This seems slightly similar to [PROTON-540](https://issues.apache.org/jira/browse/PROTON-540).

### Full backtrace
```
Thread 4 (Thread 0x7ff69c1d1700 (LWP 11203)):
#0  sem_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/sem_wait.S:85
#1  0x00007ff69f57b9c0 in qpidBridgeMamaIoImpl_dispatchThread (closure=<optimized out>) at mama/c_cpp/src/c/bridge/qpid/io.c:246
#2  0x00007ff6a044ddc5 in start_thread (arg=0x7ff69c1d1700) at pthread_create.c:308
#3  0x00007ff69fc7121d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113

Thread 3 (Thread 0x7ff69c9d2700 (LWP 11202)):
#0  0x00007ff69fc68943 in select () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007ff69f581ed2 in dispatchEntry (closure=0x7eed60) at common/c_cpp/src/c/timers.c:148
#2  0x00007ff6a044ddc5 in start_thread (arg=0x7ff69c9d2700) at pthread_create.c:308
#3  0x00007ff69fc7121d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113

Thread 2 (Thread 0x7ff6a0b11740 (LWP 11201)):
#0  sem_timedwait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/sem_timedwait.S:101
#1  0x00007ff6a06bc0aa in wsem_timedwait (sem=0x7ed730, timeoutval=<optimized out>) at common/c_cpp/src/c/wSemaphore.c:56
#2  0x00007ff6a06ba862 in wombatQueue_dispatchInt (queue=0x7ed730, data=0x0, closure=0x0, isTimed=<optimized out>, timout=<optimized out>) at common/c_cpp/src/c/queue.c:273
#3  0x00007ff69f57d460 in qpidBridgeMamaQueue_dispatch (queue=0x7ed6c0) at mama/c_cpp/src/c/bridge/qpid/queue.c:265
#4  0x00007ff6a0690df7 in mama_start (bridgeImpl=0x7ed1b0) at mama/c_cpp/src/c/mama.c:1581
#5  0x0000000000403860 in main (argc=<optimized out>, argv=<optimized out>) at mama/c_cpp/src/examples/c/mamalistenc.c:362

Thread 1 (Thread 0x7ff69b3a2700 (LWP 11204)):
#0  0x00007ff69f338ce5 in pn_class_compare (clazz=0x0, a=0x8fed90, b=0x8299e0) at /usr/src/debug/qpid-proton-0.10/proton-c/src/object/object.c:162
#1  0x00007ff69f338d19 in pn_class_equals (clazz=<optimized out>, a=<optimized out>, b=b@entry=0x8299e0) at /usr/src/debug/qpid-proton-0.10/proton-c/src/object/object.c:171
#2  0x00007ff69f339286 in pn_list_index (list=0x818b80, value=value@entry=0x8299e0) at /usr/src/debug/qpid-proton-0.10/proton-c/src/object/list.c:88
#3  0x00007ff69f3521f7 in pni_pump_in (messenger=messenger@entry=0x817ef0, address=<optimized out>, receiver=receiver@entry=0x8299e0) at /usr/src/debug/qpid-proton-0.10/proton-c/src/messenger/messenger.c:1039
#4  0x00007ff69f352d26 in pn_messenger_process_delivery (messenger=messenger@entry=0x817ef0, event=event@entry=0x7ff69402aea0) at /usr/src/debug/qpid-proton-0.10/proton-c/src/messenger/messenger.c:1246
#5  0x00007ff69f3545b3 in pn_messenger_process_events (messenger=messenger@entry=0x817ef0) at /usr/src/debug/qpid-proton-0.10/proton-c/src/messenger/messenger.c:1302
#6  0x00007ff69f354a30 in pni_connection_readable (sel=0x81cdf0) at /usr/src/debug/qpid-proton-0.10/proton-c/src/messenger/messenger.c:268
#7  0x00007ff69f354b70 in pn_messenger_process (messenger=messenger@entry=0x817ef0) at /usr/src/debug/qpid-proton-0.10/proton-c/src/messenger/messenger.c:1367
#8  0x00007ff69f354d31 in pn_messenger_tsync (messenger=0x817ef0, predicate=0x7ff69f351960 <pn_messenger_rcvd>, timeout=<optimized out>) at /usr/src/debug/qpid-proton-0.10/proton-c/src/messenger/messenger.c:1439
#9  0x00007ff69f3552e5 in pn_messenger_recv (messenger=0x817ef0, n=<optimized out>) at /usr/src/debug/qpid-proton-0.10/proton-c/src/messenger/messenger.c:2206
#10 0x00007ff69f57dfa8 in qpidBridgeMamaTransportImpl_dispatchThread (closure=0x7f5800) at mama/c_cpp/src/c/bridge/qpid/transport.c:1262
#11 0x00007ff6a044ddc5 in start_thread (arg=0x7ff69b3a2700) at pthread_create.c:308
#12 0x00007ff69fc7121d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113
```
### Recreation details
1. **start broker**: `qpidd --auth no --topic-patterns MAMA.*  -t`
2. **start publisher**: `capturereplayc  -m qpid -tport matt_broker -S MATT -f playback.mplay -dictionary dict.dict`
3. **start subscriber**: `mamalistenc -S MATT -m qpid -tport matt_broker -f syms.txt`
4. *bounce your subscriber a few times as issue is infrequent*

**Comment by fquinner** [comment]
Haven't seen this since the increased timeout so closing off, if it comes back we can reopen.
