### ISSUE TITLE
crash in mamaTransport_destroy

### ISSUE THREAD

**Issue by btorpey** [OpenMAMA/OpenMAMA#293]
# crash in mamaTransport_destroy
## Summary
mamaproducer_v2 crashes in mamaTransport_destroy

## Areas Affected
- [x] MAMAC
- [ ] MAMACPP
- [ ] MAMADOTNET
- [ ] MAMAJNI
- [ ] MAMDA
- [ ] MAMDACPP
- [ ] MAMDADOTNET
- [ ] MAMDAJNI
- [ ] Visual Studio
- [ ] SCons
- [ ] Unit Tests
- [ ] Examples

## Details
mamaproducer_v2 crashes in mamaTransport_destroy

**Comment by btorpey** [comment]
Opening a new issue, since #267 has gotten confused with other issues.

In my tests, mamaproducer_v2 crashes at shutdown consistently, with the following stack trace:

```
#0  0x00007ffb36f1bc4f in wtable_for_each (table=0x7ffb28034190, cb=0x7ffb3626c0a1 <endpointPoolImpl_destroySubTable>, 
    closure=0x7ffb36271cf5) at common/c_cpp/src/c/wtable.c:60
        b = 0x7ffd611f39e0
        i = 0
        wtable = 0x7ffb28034190
        size = 67108864
#1  0x00007ffb3626c0d7 in endpointPoolImpl_destroySubTable (table=0x7ffb280345b0, data=0x7ffb28034190, 
    key=0x7ffb280346a0 "amqp://127.0.0.1:6666", closure=0x7ffb36271cf5) at mama/c_cpp/src/c/bridge/qpid/endpointpool.c:571
No locals.
#2  0x00007ffb36f1bc88 in wtable_for_each (table=0x7ffb280345b0, cb=0x7ffb3626c0a1 <endpointPoolImpl_destroySubTable>, 
    closure=0x7ffb36271cf5) at common/c_cpp/src/c/wtable.c:64
        next = 0x0
        b = 0x7ffb28034680
        i = 4
        wtable = 0x7ffb280345b0
        size = 16
#3  0x00007ffb3626c0d7 in endpointPoolImpl_destroySubTable (table=0xf68540, data=0x7ffb280345b0, 
    key=0x7ffb280346e0 "MAMA_TOPIC58", closure=0x7ffb36271cf5) at mama/c_cpp/src/c/bridge/qpid/endpointpool.c:571
No locals.
#4  0x00007ffb36f1bc88 in wtable_for_each (table=0xf68540, cb=0x7ffb3626c0a1 <endpointPoolImpl_destroySubTable>, 
    closure=0x7ffb36271cf5) at common/c_cpp/src/c/wtable.c:64
        next = 0x0
        b = 0x7ffb280346c0
        i = 1
        wtable = 0xf68540
        size = 128
#5  0x00007ffb3626b9e0 in endpointPool_destroyWithCallback (endpoints=0xf680e0, callback=0x7ffb36271cf5 <destroyQpidEndpoint>)
    at mama/c_cpp/src/c/bridge/qpid/endpointpool.c:203
        impl = 0xf680e0
#6  0x00007ffb3627005f in qpidBridgeMamaTransport_destroy (transport=0xe13300) at mama/c_cpp/src/c/bridge/qpid/transport.c:297
        impl = 0xe13300
        status = MAMA_STATUS_OK
        next = 0x0
#7  0x00007ffb36f0a0e5 in mamaTransport_destroy (transport=0xe12eb0) at mama/c_cpp/src/c/transport.c:1269
        i = 0
        allTransportsValid = 1
#8  0x0000000000404e49 in producerShutdown (msgVar=0) at mama/c_cpp/src/testtools/performance/c/mamaproducerc_v2.c:1055
        status = MAMA_STATUS_OK
        i = 0
        j = 1
        nsec = 0
        __FUNCTION__ = "producerShutdown"
#9  0x000000000040484c in main (argc=14, argv=0x7ffd611f39e8) at mama/c_cpp/src/testtools/performance/c/mamaproducerc_v2.c:984
        transportName = 0x7ffd611f5031 "pub"
        middleware = 0x7ffd611f5038 "qpid"
        nowString = "2017/06/21 - 10:50:33", '\000' <repeats 18 times>
        msgInterval = 0.5
        randValCounts = 1
        msgSize = 200
        msgVar = 0
        lastStep = 1498056844575550551
        randVal = 0
        randNum = 1498056844449560950
        nsec = 937234
        lastDisplay = 1498056844071586549
        numPoints = 1652
        i = 126
        pubIndex = 58
        start = 1498056844449560950
        end = 1498056844575550551
        nowTsc = 224783277834
        ts = {tv_sec = 1498056844, tv_nsec = 575550551}
        pubTickArray = 0xdee010
        numMsgs = 106058
        diffUsec = 0
        nowTime = 0x1262350
        targetRate = 1000
        usecStatInterval = 1000000
        nsecStatInterval = 1000000000
        tscStatInterval = 2659965000
        pubNsec = 62766
        reached = 1 '\001'
        tscStepInterval = 0
        nsecStepInterval = 10000000000
        startStep = 1498056643446387846
        __FUNCTION__ = "main"
```

Similar crashes occur in any other programs using the qpid transport when calling mamaTransport_destroy.

**Comment by fquinner** [comment]
Dup of https://github.com/OpenMAMA/OpenMAMA/issues/267

**Comment by bill-torpey** [comment]
Curious why you closed this?  Crash still reliably occurs w/qpid.

(While this is a dup of #267, that issue was already closed.)

**Comment by fquinner** [comment]
#267 is not closed.

**Comment by bill-torpey** [comment]
Sorry -- I misread the button.  Never mind ...
